# Generated by Django 4.2.1 on 2023-05-30 20:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0016_alter_category_options_remove_product_category_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Category'},
        ),
    ]
