# Generated by Django 4.2.1 on 2023-05-30 20:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0017_alter_category_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='order',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='product',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.DeleteModel(
            name='OrderItem',
        ),
    ]
