# Generated by Django 4.2.1 on 2023-06-05 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0022_remove_orderitem_order_remove_orderitem_product_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='lga',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='state',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
