# Generated by Django 4.2.1 on 2023-06-05 23:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0030_userprofile_lga_userprofile_state'),
        ('store', '0023_product_lga_product_state'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='lga',
        ),
        migrations.RemoveField(
            model_name='product',
            name='state',
        ),
        migrations.AddField(
            model_name='product',
            name='userprofile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='userprofile.userprofile'),
        ),
    ]
