# Generated by Django 4.2.1 on 2023-06-28 22:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0026_category_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='name',
        ),
    ]
