# Generated by Django 4.2.1 on 2023-06-28 23:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0028_testing'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Testing',
        ),
    ]
