# Generated by Django 4.2.1 on 2023-06-30 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0029_delete_testing'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='condition',
            field=models.CharField(blank=True, choices=[('1', 'New'), ('2', 'Used')], max_length=50, null=True),
        ),
    ]
