# Generated by Django 4.2.1 on 2023-07-06 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0034_product_brand'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='model',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
