# Generated by Django 4.2.1 on 2023-05-29 22:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0013_alter_customuser_options_alter_customuser_managers_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
