# Generated by Django 4.2.1 on 2023-05-29 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0014_delete_customuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='is_user',
            field=models.BooleanField(default=False),
        ),
    ]
