# Generated by Django 4.2.1 on 2023-05-29 23:20

import django.contrib.auth.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0015_userprofile_is_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='is_vendor',
            field=models.BooleanField(default=False, verbose_name=django.contrib.auth.models.User),
        ),
    ]
