# Generated by Django 4.2.1 on 2023-05-30 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0019_alter_userprofile_is_vendor'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='WhatsApp',
            field=models.PositiveBigIntegerField(default=2),
            preserve_default=False,
        ),
    ]
