# Generated by Django 4.2.1 on 2023-05-30 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0020_userprofile_whatsapp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='WhatsApp',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
    ]
