# Generated by Django 4.2.1 on 2023-05-30 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0021_alter_userprofile_whatsapp'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='WhatsApp',
            new_name='company_whatsapp_number',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='company_email',
            field=models.EmailField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='company_image',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/profile_pic'),
        ),
    ]
