# Generated by Django 4.2.1 on 2023-05-30 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0025_remove_customuser_phone_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='is_vendor',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='is_vendor',
            field=models.BooleanField(default=False, verbose_name='Click if you are Vendor'),
        ),
    ]
