# Generated by Django 4.2.1 on 2023-06-02 15:47

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0026_userprofile_is_vendor_alter_customuser_is_vendor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='company_whatsapp_number',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None, verbose_name='WhatsApp'),
        ),
    ]
