# Generated by Django 4.2.1 on 2023-06-04 02:56

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0027_alter_userprofile_company_whatsapp_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='company_phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None, verbose_name='Phone Number'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='company_whatsapp_number',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='Whatsapp'),
        ),
    ]
