# Generated by Django 4.2.1 on 2023-06-04 03:04

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0028_userprofile_company_phone_number_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='company_phone_number',
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='company_whatsapp_number',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None, verbose_name='WhatsApp'),
        ),
    ]
