# Generated by Django 4.2.1 on 2023-06-06 14:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0030_userprofile_lga_userprofile_state'),
    ]

    operations = [
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='state',
            field=models.OneToOneField(blank=True, max_length=20, null=True, on_delete=django.db.models.deletion.CASCADE, to='userprofile.state'),
        ),
    ]
