# Generated by Django 4.2.1 on 2023-06-13 18:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0035_userprofile_vendor_activation_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='last_vendor_set_date',
        ),
    ]
