# Generated by Django 4.2.1 on 2023-06-13 19:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0036_remove_userprofile_last_vendor_set_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='vendor_activation_date',
        ),
    ]
