# Generated by Django 4.2.1 on 2023-06-16 12:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0037_remove_userprofile_vendor_activation_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='company_email',
        ),
    ]
