# Generated by Django 4.2.1 on 2023-06-27 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0039_alter_userprofile_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='vendor_expiry_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
