# Generated by Django 4.2.1 on 2023-06-30 22:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0040_userprofile_vendor_expiry_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='vendor_expiry_time',
        ),
    ]
